# Generated by Django 4.2 on 2025-02-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crawleddata",
            old_name="content",
            new_name="address",
        ),
    ]
